### ISSUE TITLE
a flexint issue only partially fixed

### ISSUE THREAD

**Issue by adl** [westes/flex#517] opened 2022-02-16 17:14 UTC
My C++17 project, using Flex 2.6.4, suffers from an issue that is only partially fixed in the current development version of Flex.

C scanners generated by Flex 2.6.4 contain the following code:
```c
/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */
#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* [...] */
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
/* [...] */
#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif
#endif /* ! C99 */
```
This causes two problems:
1. `__STDC_VERSION__` is undefined in C++, so when a C scanner is compiled as C++, the fallback definitions are always used and might be pointing to the wrong types
2. the unused `SIZE_MAX` macro is defined in a non-conformant way, triggering errors from the preprocessor (on architectures where (`SIZE_MAX` hasn't bet previously defined somehow).  In my case, an OpenBSD dev (@marcespie) sent the following trace:

```
robin_hood.hh:103:5: error: token is not a valid binary operator in a preprocessor subexpression
#if SIZE_MAX == UINT32_MAX
    ^~~~~~~~
scanaut.cc:299:42: note: expanded from macro 'SIZE_MAX'
#define SIZE_MAX               (~(size_t)0)
                                ~~~~~~~~~^
```

This second point was apparently fixed in 5574881ff4c9b08c73b6acc0087d6046c2b48de5, but the first issue remains: `<inttypes.h>` is always ignored in C++ mode, even if it's very likely to be present.

Currently I'm using the following workaround in my scanners to force `<inttypes.h>` to be included and to avoid the `SIZE_MAX` problem above.  My `configure` script tests for `inttypes.h` and my scanner starts with:
```c++
%top{
#include "config.h"
/* Flex 2.6.4's test for inttypes.h relies on __STDC_VERSION__
   which is undefined in C++.   So without that, it will define
   its own integer types, including a broken SIZE_MAX definition.
   So let's define __STDC_VERSION__ to make sure <inttypes.h> gets
   included. */
#if HAVE_INTTYPES_H && !(defined __STDC_VERSION__)
#  define __STDC_VERSION__ 199901L
#endif
}
```
It would be nice if Flex had a test for `inttypes.h` that does not solely rely on `__STDC_VERSION__`.  For instance an option would be to additionally use the [`__has_include` macro](https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html) when it is available (see also [this](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2673.pdf) for a list of compilers already supporting it).

**Comment by Explorer09** [comment] 2022-04-08 03:54
@adl 

1. C++11 standard says this: "Whether `__STDC_VERSION__` is predefined and if so, what its value is, are implementation-defined." So your saying it's undefined is not technically accurate, although it's indeed an issue when flex's skeleton didn't address C++ environment.
2. How about adding an include statement like this?

```c++
#if defined(__cplusplus) && __cplusplus >= 201103L
#include <cstdint>
#endif
```

3. `__has_include(<cstdint>)` would be an overkill since the macro was introduced in C++17 but the `<cstdint>` header had been standardized already in C++11.
4. If you were using `SIZE_MAX` in a preprocessor conditional, you should already include `stdint.h` or `inttypes.h`, or else the token would be undefined and you would still get a compile error. That `SIZE_MAX` is defined as `(~(size_t)0)` in skeleton is irrelevant to your problem -- your scanner code had been broken already.

**Comment by adl** [comment] 2022-06-16 16:27
Sorry for the delay in my answer.  (GitHub is notifying me on a mail box I do not read regularly.)

The proposed include statement for `<cstdint>` looks fine to me.

(My suggestion about `__has_include` was to actually use this even in C when it is available.  Which would have fixed the C++ case as well.  But your proposal is probably safer.)

Regarding your point 4, [here is how OpenBSD defines SIZE_MAX](https://github.com/lattera/openbsd/blob/bada9b8d31a004772af7557526ea2f0c2caa6936/sys/sys/stdint.h#L190):
```c
#ifndef	SIZE_MAX
#define	SIZE_MAX		UINTPTR_MAX
#endif
```
And here is [how MinGW does it](https://github.com/mirror/mingw-w64/blob/b33bcd6aba7a789e6e3ce66114651a92b9bcb170/mingw-w64-headers/crt/stdint.h#L152):
```c
#ifndef SIZE_MAX
#ifdef _WIN64
#define SIZE_MAX UINT64_MAX
#else
#define SIZE_MAX UINT32_MAX
#endif
#endif
```

So these are conditional definitions.  If they get included after Flex 2.6.4 has defined its `SIZE_MAX` macro, the code will continue with Flex's version and break on certain use-cases.  (On my Linux system, the system's definition of `SIZE_MAX` overrides the Flex definition, so I did not notice.)  So I guess one work around would be to include the system's definition in the `%top` part of the lexer.  That might be cleaner than the workaround I have now.

**Comment by Explorer09** [comment] 2022-06-16 17:48
> Regarding your point 4......
> So these are conditional definitions. If they get included after Flex 2.6.4 has defined its SIZE_MAX macro, the code will continue with Flex's version and break on certain use-cases.

That is the main reason Flex includes <stdint.h> or <inttypes.h> before trying to define its own `SIZE_MAX` constant. There's no need for the user to include the said headers (although including them wouldn't hurt); Flex scanner's include lines would just do the right thing.

**Comment by adl** [comment] 2022-06-16 18:44
> That is the main reason Flex includes <stdint.h> or <inttypes.h> before trying to define its own `SIZE_MAX` constant. There's no need for the user to include the said headers (although including them wouldn't hurt); Flex scanner's include lines would just do the right thing.

Not sure if you are talking about Flex 2.6.4's generated code or something else here.  Because the excerpt in my original message shows that `SIZE_MAX` is defined only when `<inttypes.h>` is **not** included.  So ultimately some of the headers I include end up actually including one of the headers defining `SIZE_MAX`: on architectures where `SIZE_MAX` is overwritten, the preprocessing code involving `SIZE_MAX` would work and on others like OpenBSD it would fail as shown.

Anyway there is nothing to fix about this now since the current development code does not output a definition of `SIZE_MAX` anymore, and your proposed C++ check will ensure that the correct header is also included when compiling in C++.

I'm only mentioning the problem with `SIZE_MAX` for the benefit of those who have to preserve compatibility with Flex 2.6.4.

**Comment by Explorer09** [comment] 2022-06-16 20:01
> Not sure if you are talking about Flex 2.6.4's generated code or something else here. Because the excerpt in my original message shows that `SIZE_MAX` is defined only when `<inttypes.h>` is **not** included.

The internal use of `SIZE_MAX` in a Flex-generated scanner should never affect user code. For user code that needs to use `SIZE_MAX`, it should include `<inttypes.h>` by the user code itself.

> So ultimately some of the headers I include ends up actually including one of the headers defining `SIZE_MAX`: on architectures where `SIZE_MAX` is overwritten, the preprocessing code involving `SIZE_MAX` would work and on others like OpenBSD it would fail as shown.

The system's `SIZE_MAX` definition should override the internal, fallback definition inside the Flex-generated scanner. That was the intended behavior. 
If `SIZE_MAX` was defined as `(~(size_t)0)` and you got an error about the preprocessor conditional, that conditional was broken already and should be fixed by including `<inttypes.h>` before the conditional.
The Flex scanner's .c is not meant to be included by any user code - that's what .h files are for.

**Comment by adl** [comment] 2022-06-17 07:43
> The system's `SIZE_MAX` definition should override the internal, fallback definition inside the Flex-generated scanner. That was the intended behavior. 

I understand that was the intent.  But the practice, as I have quoted above, is that some systems like OpenBSD or MinGW do not redefine `SIZE_MAX` if it is already defined.  So even code that include `<inttype.h>` before doing `#if SIZE_MAX == UINT32_MAX` will break if `SIZE_MAX` has been predefined in a non-conformant way before the `<inttype.h>` inclusion.

**Comment by Explorer09** [comment] 2022-06-17 07:54
> [S]ome systems like OpenBSD or MinGW do not redefine `SIZE_MAX` if it is already defined. So even code that include `<inttypes.h>` before doing `#if SIZE_MAX == UINT32_MAX` will break if `SIZE_MAX` has been predefined in a non-conformant way before the `<inttypes.h>` inclusion.

Then fix the non-conformant systems, dammit. That's not Flex's fault.

**Comment by marcespie** [comment] 2022-06-17 08:22
> Then fix the non-conformant systems, dammit. That's not Flex's fault.

Can you tell me where it says in the C standard that's non-conformant ?
In n2912, 7.1.3, item 5 clearly states that defining SIZE_MAX in your program shouldn't happen, and it goes on to say the same thing in different ways several times in the introductory paragraphs for standard headers.

So the #ifdef don't affect conformant programs.

Please point me to the paragraph of the standard that explicitly says that implementation is non-conformant.

**Comment by Explorer09** [comment] 2022-06-17 08:50
@marcespie `SIZE_MAX` is defined in `<stdint.h>` starting with C99. Flex includes `<stdint.h>` or `<inttypes.h>` before defining its own fallback `SIZE_MAX` macro. There is no chance that Flex's definition would override the definition from the system. The more likely scenario is that, either the `<stdint.h>` header wasn't included properly (which I already addressed in one of the comments above), or the compiler predefined the macro in a way that cannot be used in the preprocessor in the first place.

**Comment by marcespie** [comment] 2022-06-17 10:19
> @marcespie Flex includes `<stdint.h>` or `<inttypes.h>` before defining its own fallback `SIZE_MAX` macro. 

No it doesn't, not in C++ mode.

Unless I missed something, there's no indication in the C++ standard that the C++ compiler shall define __STDC_VERSION__.  You have to figure out whether stdint.h is present in some other way (you could most certainly try for the C++ version, for instance. I'm pretty sure somewhere around C++14, the standard started including the headers from C99.

which is precisely what was causing the problem in Alexandre's case.

**Closed** 2022-06-17 11:46 UTC

**Comment by Explorer09** [comment] 2022-06-17 11:47
@marcespie Would you please read my previous comments? I said I am aware of the issue in C++ mode.

It's this statement from Alexandre that didn't match what happened:

> So even code that include `<inttypes.h>` before doing `#if SIZE_MAX == UINT32_MAX` will break if `SIZE_MAX` has been predefined in a non-conformant way before the `<inttypes.h>` inclusion.

`SIZE_MAX` was not "predefined" by Flex. It's the inttypes.h header that wasn't got included that caused the compile error.

And see #531 for how to fix that. (Thanks westes for merging that just now.)

**Comment by Explorer09** [comment] 2022-06-17 14:58
@marcespie I'm not saying OpenBSD is not comformant. I was talking about a hypothetical system where ”`SIZE_MAX` has been predefined in a non-conformant way before the <inttypes.h> inclusion”. It _is_ possible for a compiler to predefine `SIZE_MAX` before inclusion of any header, and I knew that it's often that limits defined in libc's header respect the definition from the compiler's header (that's why `SIZE_MAX` has been conditionally defined in OpenBSD's header -- not overriding the compiler's definition). If there exists any compiler that `SIZE_MAX` was predefined in a non-conformant way, then that's the non-conformance I was talking about.

**Comment by adl** [comment] 2022-06-20 09:54
> It's this statement from Alexandre that didn't match what happened:
> 
> > So even code that include `<inttypes.h>` before doing `#if SIZE_MAX == UINT32_MAX` will break if `SIZE_MAX` has been predefined in a non-conformant way before the `<inttypes.h>` inclusion.
> 
> `SIZE_MAX` was not "predefined" by Flex. It's the inttypes.h header that wasn't got included that caused the compile error.

There must be some misunderstanding.

One thing that I keep writing since the beginning is a version number.  Flex 2.6.4's generated scanners either include `<inttypes.h>` **or** they define `SIZE_MAX`.  But they do not do both.  Just read the generated code posted in the first comment: the `SIZE_MAX` definition is in the *else* branch while the `include` is in the *then* branch. So in this case saying that `<inttypes.h>` wasn't included (by Flex's generated code) is the same as saying that `SIZE_MAX` was defined.

Now, as I wrote in my very first comment, I'm aware that this changed with commit 5574881ff4c9b08c73b6acc0087d6046c2b48de5.  Future Flex scanners do not define `SIZE_MAX` so this won't be an issue.  Additionally, #531 fixed the inclusion of the right headers for C++ mode, so even the `typedef`s won't risk being wrong (rightfully closing this issue).  This is all very good, thank you!

What remains, and what I was talking about, is simply a portability issue. If the following four conditions happen:
1. one is *still* using Flex 2.6.4 to generate scanners
2. one is compiling in C++ mode (hence the generated scanner will not include `<inttypes.h>` and will define `SIZE_MAX`), 
3. the scanner includes some third-party headers after that `SIZE_MAX` definition:
   ```c++
   %{
   #include <third-party.hh>
   %}
   ```
   and this third-party header contains something like
   ```c++
   #include <cstdint>
   #if SIZE_MAX == UINT32_MAX
   //...
   #endif
   ```
4. one is compiling on a system (such as OpenBSD) where `#include <cstdint>` will not override the `SIZE_MAX` definition introduced by Flex.

Then the compilation will fail.   This is not a hypothetical situation, but the one that triggered this bug report.  In this case, a temporary fix (until one can require a more recent Flex version) is to include `<cstdint>` in `%top`.  I was simply trying to document that for the benefit of people googling the same issue in the future.

**Comment by Explorer09** [comment] 2022-06-20 11:16
@adl If you have written that as a "steps to reproduce" section of the bug report, you could save us time trying to argue where the problem was (or whether it was a bug after all).

I would argue that a better workaround for the "portability" case you mentioned is to move the `#include` third-party header lines to the `%top` block:

```c
%top{
#include <third-party.hh>
}
```
Most coding styles for C-like languages would require include lines to be placed at the top of the files, after copyright info comments (if any) and before Flex definitions. There are macros that only work when they are defined at the top such as [feature test macros](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html), and `config.h` generated by build systems is also expected to be included as the first `#include` line. In other words, putting the `#include` lines at the top has been a good practice from the start.
