### ISSUE TITLE
quote in comments not properly recognized

### ISSUE THREAD

**Issue by DenisExcoffier** [westes/flex#102] opened 2016-10-25 18:30 UTC
Hello,

The following piece of code (see below) was ok
under flex-2.6.1, but now outputs:

cm1.lex:11: EOF encountered inside an action

under flex-2.6.2. Please note the quote within
the //-kind-of comment

%{
%}
%S INSIDE
%%
"<inside>" {
    // '
    ECHO; BEGIN INSIDE;
  };
<INSIDE>"</inside>" { ECHO; BEGIN INITIAL; };
%%

**Comment by DenisExcoffier** [comment] 2016-10-25 18:41
It was supposed to be "beg of inside" instead of "" (1st occurrence) and "end of inside" (2nd occurrence). In fact i wrote '<' + 'inside' + '>' and '</' + 'inside' + '>' (both inside double quotes) but this got removed. This presentation system is perhaps not the best for insertion of code.
Oops, i just discovered the "Insert code" button... next time.

Hoping the issue/bug-report is nevertheless understandable.

**Comment by westes** [comment] 2016-11-04 23:52
@DemiMarie could you have a look at this?

**Comment by DemiMarie** [comment] 2016-11-08 14:30
I know what the problem is: somewhere I changed the rules for string and character literals to extend across multiple lines, so as to handle line continuations correctly.  Since Flex does not understand `//` comments, this problem resulted.

I will make a patch.

**Comment by westes** [comment] 2016-12-29 22:53
This has been fixed in master and will be included in the next release of flex.

**Closed by westes** 2016-12-29 22:53 UTC
