### ISSUE TITLE
compiler warnings during make check

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#200] opened 2017-05-02 10:53 UTC
~~~
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:20:1: warning: "yy_create_buffer" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:20:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:21:1: warning: "yy_delete_buffer" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:21:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:22:1: warning: "yy_scan_buffer" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:22:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:23:1: warning: "yy_scan_string" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:23:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:24:1: warning: "yy_scan_bytes" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:24:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:25:1: warning: "yy_init_buffer" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:25:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:26:1: warning: "yy_flush_buffer" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:26:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:27:1: warning: "yy_load_buffer_state" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:27:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:28:1: warning: "yy_switch_to_buffer" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:28:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:29:1: warning: "yypush_buffer_state" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:29:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:30:1: warning: "yypop_buffer_state" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:30:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:31:1: warning: "yyensure_buffer_stack" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:31:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:32:1: warning: "yylex" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:32:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:33:1: warning: "yyrestart" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:33:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:34:1: warning: "yylex_init" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:34:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:35:1: warning: "yylex_init_extra" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:35:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:36:1: warning: "yylex_destroy" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:36:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:37:1: warning: "yyget_debug" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:37:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:38:1: warning: "yyset_debug" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:38:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:39:1: warning: "yyget_extra" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:39:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:40:1: warning: "yyset_extra" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:40:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:41:1: warning: "yyget_in" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:41:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:42:1: warning: "yyset_in" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:42:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:43:1: warning: "yyget_out" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:43:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:44:1: warning: "yyset_out" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:44:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:45:1: warning: "yyget_leng" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:45:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:46:1: warning: "yyget_text" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:46:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:47:1: warning: "yyget_lineno" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:47:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:48:1: warning: "yyset_lineno" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:48:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:50:1: warning: "yyget_column" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:50:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:51:1: warning: "yyset_column" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:51:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:53:1: warning: "yywrap" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:53:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:55:1: warning: "yyalloc" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:55:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:56:1: warning: "yyrealloc" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:56:1: warning: this is the location of the previous definition
In file included from multiple_scanners_r_main.c:25:
multiple_scanners_r_2.h:57:1: warning: "yyfree" redefined
In file included from multiple_scanners_r_main.c:24:
multiple_scanners_r_1.h:57:1: warning: this is the location of the previous definition
~~~

The [automake manual][1] says something that may help here:

> For `yacc`, simply managing locking is insufficient. The output of `yacc` always uses the same symbol names internally, so it isn’t possible to link two `yacc` parsers into the same executable.
>
>We recommend using the following renaming hack used in `gdb`: 
```c
#define yymaxdepth c_maxdepth
#define yyparse c_parse
#define yylex   c_lex
#define yyerror c_error
#define yylval  c_lval
#define yychar  c_char
#define yydebug c_debug
#define yypact  c_pact
#define yyr1    c_r1
#define yyr2    c_r2
#define yydef   c_def
#define yychk   c_chk
#define yypgo   c_pgo
#define yyact   c_act
#define yyexca  c_exca
#define yyerrflag c_errflag
#define yynerrs c_nerrs
#define yyps    c_ps
#define yypv    c_pv
#define yys     c_s
#define yy_yys  c_yys
#define yystate c_state
#define yytmp   c_tmp
#define yyv     c_v
#define yy_yyv  c_yyv
#define yyval   c_val
#define yylloc  c_lloc
#define yyreds  c_reds
#define yytoks  c_toks
#define yylhs   c_yylhs
#define yylen   c_yylen
#define yydefred c_yydefred
#define yydgoto  c_yydgoto
#define yysindex c_yysindex
#define yyrindex c_yyrindex
#define yygindex c_yygindex
#define yytable  c_yytable
#define yycheck  c_yycheck
#define yyname   c_yyname
#define yyrule   c_yyrule
```
> For each define, replace the `c_` prefix with whatever you like. These defines work for `bison`, `byacc`, and traditional `yacc`s. 

[1]:https://www.gnu.org/software/automake/manual/html_node/Yacc-and-Lex.html

**Comment by westes** [comment] 2017-05-02 10:58
Is this the same issue as #142?

On Tuesday,  2 May 2017,  3:53 am -0700, Simon Sobisch <notifications@github.com> wrote:

> ~~~
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:20:1: warning: "yy_create_buffer" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:20:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:21:1: warning: "yy_delete_buffer" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:21:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:22:1: warning: "yy_scan_buffer" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:22:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:23:1: warning: "yy_scan_string" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:23:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:24:1: warning: "yy_scan_bytes" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:24:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:25:1: warning: "yy_init_buffer" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:25:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:26:1: warning: "yy_flush_buffer" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:26:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:27:1: warning: "yy_load_buffer_state" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:27:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:28:1: warning: "yy_switch_to_buffer" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:28:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:29:1: warning: "yypush_buffer_state" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:29:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:30:1: warning: "yypop_buffer_state" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:30:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:31:1: warning: "yyensure_buffer_stack" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:31:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:32:1: warning: "yylex" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:32:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:33:1: warning: "yyrestart" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:33:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:34:1: warning: "yylex_init" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:34:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:35:1: warning: "yylex_init_extra" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:35:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:36:1: warning: "yylex_destroy" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:36:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:37:1: warning: "yyget_debug" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:37:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:38:1: warning: "yyset_debug" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:38:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:39:1: warning: "yyget_extra" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:39:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:40:1: warning: "yyset_extra" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:40:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:41:1: warning: "yyget_in" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:41:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:42:1: warning: "yyset_in" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:42:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:43:1: warning: "yyget_out" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:43:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:44:1: warning: "yyset_out" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:44:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:45:1: warning: "yyget_leng" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:45:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:46:1: warning: "yyget_text" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:46:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:47:1: warning: "yyget_lineno" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:47:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:48:1: warning: "yyset_lineno" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:48:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:50:1: warning: "yyget_column" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:50:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:51:1: warning: "yyset_column" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:51:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:53:1: warning: "yywrap" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:53:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:55:1: warning: "yyalloc" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:55:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:56:1: warning: "yyrealloc" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:56:1: warning: this is the location of the previous definition
> In file included from multiple_scanners_r_main.c:25:
> multiple_scanners_r_2.h:57:1: warning: "yyfree" redefined
> In file included from multiple_scanners_r_main.c:24:
> multiple_scanners_r_1.h:57:1: warning: this is the location of the previous definition
> ~~~
> 
> The [automake manual][1] says something that may help here:
> 
> > For `yacc`, simply managing locking is insufficient. The output of `yacc` always uses the same symbol names internally, so it isn’t possible to link two `yacc` parsers into the same executable.
> >
> >We recommend using the following renaming hack used in `gdb`: 
> ```c
> #define yymaxdepth c_maxdepth
> #define yyparse c_parse
> #define yylex   c_lex
> #define yyerror c_error
> #define yylval  c_lval
> #define yychar  c_char
> #define yydebug c_debug
> #define yypact  c_pact
> #define yyr1    c_r1
> #define yyr2    c_r2
> #define yydef   c_def
> #define yychk   c_chk
> #define yypgo   c_pgo
> #define yyact   c_act
> #define yyexca  c_exca
> #define yyerrflag c_errflag
> #define yynerrs c_nerrs
> #define yyps    c_ps
> #define yypv    c_pv
> #define yys     c_s
> #define yy_yys  c_yys
> #define yystate c_state
> #define yytmp   c_tmp
> #define yyv     c_v
> #define yy_yyv  c_yyv
> #define yyval   c_val
> #define yylloc  c_lloc
> #define yyreds  c_reds
> #define yytoks  c_toks
> #define yylhs   c_yylhs
> #define yylen   c_yylen
> #define yydefred c_yydefred
> #define yydgoto  c_yydgoto
> #define yysindex c_yysindex
> #define yyrindex c_yyrindex
> #define yygindex c_yygindex
> #define yytable  c_yytable
> #define yycheck  c_yycheck
> #define yyname   c_yyname
> #define yyrule   c_yyrule
> ```
> > For each define, replace the `c_` prefix with whatever you like. These defines work for `bison`, `byacc`, and traditional `yacc`s. 
> 
> [1]:https://www.gnu.org/software/automake/manual/html_node/Yacc-and-Lex.html
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/200

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment] 2017-05-02 11:06
Yes, you may close it as duplicate - but I'd suggest to copy the hint of the autoconf manual to the original post in this case.

**Comment by westes** [comment] 2017-05-02 11:31
There's a bug in some of the later code generation that doesn't include the prefixing stuff like it should.

On Tuesday,  2 May 2017,  4:06 am -0700, Simon Sobisch <notifications@github.com> wrote:

> Yes, you may close it as duplicate - but I'd suggest to copy the hint of the autoconf manual to the original post in this case.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/200#issuecomment-298605937

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment] 2017-05-02 19:01
Duplicate of #142

**Closed by westes** 2017-05-02 19:01 UTC
